### ISSUE TITLE
Add bare-metal support

### ISSUE THREAD

**Issue by vanneback** [elastisys/ck8s-cluster#1]
- [x] elastisys/ck8s-cluster#5 
- [ ] elastisys/ck8s-cluster#6 
- [ ] elastisys/ck8s-cluster#7 
- [x] elastisys/ck8s-cluster#8 
- [ ] elastisys/ck8s-cluster#9
- [ ] elastisys/ck8s-base-vm#22 
- [ ] elastisys/ck8s-cluster#11 
- [x] elastisys/ck8s-cluster#12 
- [x] elastisys/ck8s-apps#119

Related, but strictly not required:
- [ ] elastisys/ck8s-cluster#20

**Comment by vanneback** [comment]
Closing because of more updated version in elastisys/ck8s-apps#212
